language: python
python:
  - "2.7"
  - "3.4"

install:
  - pip install sphinx sphinx_rtd_theme
  - pip install -r requirements.txt

script:
  - python setup.py install
  - pytest

after_success:
  - pushd docs; make gh-pages dry; popd

